apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-exporter
  name: jenkins-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-exporter
  template:
    metadata:
      labels:
        app: jenkins-exporter
    spec:
      containers:
      - image: michaelvl/jenkins_exporter
        name: exporter
        env:
        - name: JENKINS_SERVER
          value: "http://jenkins:8080"
        - name: VIRTUAL_PORT
          value: "9100"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-exporter
  name: jenkins-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/'
    prometheus.io/port: '9100'
spec:
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: jenkins-exporter
